spring.application.name=backend

# =========================================
# PostgreSQL
# =========================================

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sagadb}
spring.datasource.username=${DB_USERNAME:saga_user}
spring.datasource.password=${DB_PASSWORD:saga_pwd}

# =========================================
# JPA / Hibernate
# =========================================

# Hibernate vérifie uniquement que les tables
# correspondent aux entités Java.
# Il ne crée/modifie/supprime aucune table.
# spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================
# INITIALISATION SQL
# =========================================

# Les tables et les données sont gérées
# directement par PostgreSQL via Docker.
spring.sql.init.mode=never

# =========================================
# EMAIL - SMTP GMAIL
# =========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.frontend.url=http://localhost:5173
